// This file was created by MAXCONVS SPM Exporter (Version 1.61) -- Friday, February 25, 2000  16:15:38 PM

	SIMPLESPRITEDEF
		SIMPLESPRITETAG  "COALS_SPRITE"
		NUMFRAMES 1
		BMINFO "COALS" "COALS.BMP" 
	ENDSIMPLESPRITEDEF

