// This file was created by MAXCONVS SPM Exporter (Version 1.56) -- Tuesday, January 05, 1999  11:44:32 AM

	SIMPLESPRITEDEF
		SIMPLESPRITETAG  "MEATTORN2_SPRITE"
		NUMFRAMES 1
		BMINFO "MEATTORN2" "MEATTORN2.BMP" 
	ENDSIMPLESPRITEDEF

