// This file was created by MAXCONVS SPM Exporter (Version 1.56) -- Tuesday, January 05, 1999  11:43:48 AM

	SIMPLESPRITEDEF
		SIMPLESPRITETAG  "MEATUA1_SPRITE"
		NUMFRAMES 1
		BMINFO "MEATUA1" "MEATUA1.BMP" 
	ENDSIMPLESPRITEDEF

